/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScrittiRouteImport } from './routes/scritti'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LibriRouteImport } from './routes/libri'
import { Route as FotografieRouteImport } from './routes/fotografie'
import { Route as FiabeRouteImport } from './routes/fiabe'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ChiSonoRouteImport } from './routes/chi-sono'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AudiolibriPerBambiniRouteImport } from './routes/audiolibri-per-bambini'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPoesieRouteImport } from './routes/admin.poesie'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminMessaggiRouteImport } from './routes/admin.messaggi'
import { Route as AdminLibriRouteImport } from './routes/admin.libri'
import { Route as AdminFotografieRouteImport } from './routes/admin.fotografie'
import { Route as AdminFiabeRouteImport } from './routes/admin.fiabe'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrittiRoute = ScrittiRouteImport.update({
  id: '/scritti',
  path: '/scritti',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LibriRoute = LibriRouteImport.update({
  id: '/libri',
  path: '/libri',
  getParentRoute: () => rootRouteImport,
} as any)
const FotografieRoute = FotografieRouteImport.update({
  id: '/fotografie',
  path: '/fotografie',
  getParentRoute: () => rootRouteImport,
} as any)
const FiabeRoute = FiabeRouteImport.update({
  id: '/fiabe',
  path: '/fiabe',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSonoRoute = ChiSonoRouteImport.update({
  id: '/chi-sono',
  path: '/chi-sono',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiolibriPerBambiniRoute = AudiolibriPerBambiniRouteImport.update({
  id: '/audiolibri-per-bambini',
  path: '/audiolibri-per-bambini',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoesieRoute = AdminPoesieRouteImport.update({
  id: '/poesie',
  path: '/poesie',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessaggiRoute = AdminMessaggiRouteImport.update({
  id: '/messaggi',
  path: '/messaggi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibriRoute = AdminLibriRouteImport.update({
  id: '/libri',
  path: '/libri',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFotografieRoute = AdminFotografieRouteImport.update({
  id: '/fotografie',
  path: '/fotografie',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFiabeRoute = AdminFiabeRouteImport.update({
  id: '/fiabe',
  path: '/fiabe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/audiolibri-per-bambini': typeof AudiolibriPerBambiniRoute
  '/auth': typeof AuthRoute
  '/chi-sono': typeof ChiSonoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/fiabe': typeof FiabeRoute
  '/fotografie': typeof FotografieRoute
  '/libri': typeof LibriRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scritti': typeof ScrittiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/fiabe': typeof AdminFiabeRoute
  '/admin/fotografie': typeof AdminFotografieRoute
  '/admin/libri': typeof AdminLibriRoute
  '/admin/messaggi': typeof AdminMessaggiRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/poesie': typeof AdminPoesieRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audiolibri-per-bambini': typeof AudiolibriPerBambiniRoute
  '/auth': typeof AuthRoute
  '/chi-sono': typeof ChiSonoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/fiabe': typeof FiabeRoute
  '/fotografie': typeof FotografieRoute
  '/libri': typeof LibriRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scritti': typeof ScrittiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/fiabe': typeof AdminFiabeRoute
  '/admin/fotografie': typeof AdminFotografieRoute
  '/admin/libri': typeof AdminLibriRoute
  '/admin/messaggi': typeof AdminMessaggiRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/poesie': typeof AdminPoesieRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts': typeof AdminPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/audiolibri-per-bambini': typeof AudiolibriPerBambiniRoute
  '/auth': typeof AuthRoute
  '/chi-sono': typeof ChiSonoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/fiabe': typeof FiabeRoute
  '/fotografie': typeof FotografieRoute
  '/libri': typeof LibriRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scritti': typeof ScrittiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/fiabe': typeof AdminFiabeRoute
  '/admin/fotografie': typeof AdminFotografieRoute
  '/admin/libri': typeof AdminLibriRoute
  '/admin/messaggi': typeof AdminMessaggiRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/poesie': typeof AdminPoesieRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audiolibri-per-bambini'
    | '/auth'
    | '/chi-sono'
    | '/contatti'
    | '/cookie-policy'
    | '/fiabe'
    | '/fotografie'
    | '/libri'
    | '/privacy'
    | '/robots.txt'
    | '/scritti'
    | '/sitemap.xml'
    | '/admin/fiabe'
    | '/admin/fotografie'
    | '/admin/libri'
    | '/admin/messaggi'
    | '/admin/newsletter'
    | '/admin/poesie'
    | '/admin/posts'
    | '/blog/$slug'
    | '/admin/'
    | '/admin/posts/$id'
    | '/admin/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audiolibri-per-bambini'
    | '/auth'
    | '/chi-sono'
    | '/contatti'
    | '/cookie-policy'
    | '/fiabe'
    | '/fotografie'
    | '/libri'
    | '/privacy'
    | '/robots.txt'
    | '/scritti'
    | '/sitemap.xml'
    | '/admin/fiabe'
    | '/admin/fotografie'
    | '/admin/libri'
    | '/admin/messaggi'
    | '/admin/newsletter'
    | '/admin/poesie'
    | '/blog/$slug'
    | '/admin'
    | '/admin/posts/$id'
    | '/admin/posts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audiolibri-per-bambini'
    | '/auth'
    | '/chi-sono'
    | '/contatti'
    | '/cookie-policy'
    | '/fiabe'
    | '/fotografie'
    | '/libri'
    | '/privacy'
    | '/robots.txt'
    | '/scritti'
    | '/sitemap.xml'
    | '/admin/fiabe'
    | '/admin/fotografie'
    | '/admin/libri'
    | '/admin/messaggi'
    | '/admin/newsletter'
    | '/admin/poesie'
    | '/admin/posts'
    | '/blog/$slug'
    | '/admin/'
    | '/admin/posts/$id'
    | '/admin/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AudiolibriPerBambiniRoute: typeof AudiolibriPerBambiniRoute
  AuthRoute: typeof AuthRoute
  ChiSonoRoute: typeof ChiSonoRoute
  ContattiRoute: typeof ContattiRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  FiabeRoute: typeof FiabeRoute
  FotografieRoute: typeof FotografieRoute
  LibriRoute: typeof LibriRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ScrittiRoute: typeof ScrittiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scritti': {
      id: '/scritti'
      path: '/scritti'
      fullPath: '/scritti'
      preLoaderRoute: typeof ScrittiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libri': {
      id: '/libri'
      path: '/libri'
      fullPath: '/libri'
      preLoaderRoute: typeof LibriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografie': {
      id: '/fotografie'
      path: '/fotografie'
      fullPath: '/fotografie'
      preLoaderRoute: typeof FotografieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiabe': {
      id: '/fiabe'
      path: '/fiabe'
      fullPath: '/fiabe'
      preLoaderRoute: typeof FiabeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-sono': {
      id: '/chi-sono'
      path: '/chi-sono'
      fullPath: '/chi-sono'
      preLoaderRoute: typeof ChiSonoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiolibri-per-bambini': {
      id: '/audiolibri-per-bambini'
      path: '/audiolibri-per-bambini'
      fullPath: '/audiolibri-per-bambini'
      preLoaderRoute: typeof AudiolibriPerBambiniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/poesie': {
      id: '/admin/poesie'
      path: '/poesie'
      fullPath: '/admin/poesie'
      preLoaderRoute: typeof AdminPoesieRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messaggi': {
      id: '/admin/messaggi'
      path: '/messaggi'
      fullPath: '/admin/messaggi'
      preLoaderRoute: typeof AdminMessaggiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/libri': {
      id: '/admin/libri'
      path: '/libri'
      fullPath: '/admin/libri'
      preLoaderRoute: typeof AdminLibriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fotografie': {
      id: '/admin/fotografie'
      path: '/fotografie'
      fullPath: '/admin/fotografie'
      preLoaderRoute: typeof AdminFotografieRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fiabe': {
      id: '/admin/fiabe'
      path: '/fiabe'
      fullPath: '/admin/fiabe'
      preLoaderRoute: typeof AdminFiabeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminPostsRoute
    }
  }
}

interface AdminPostsRouteChildren {
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminRouteChildren {
  AdminFiabeRoute: typeof AdminFiabeRoute
  AdminFotografieRoute: typeof AdminFotografieRoute
  AdminLibriRoute: typeof AdminLibriRoute
  AdminMessaggiRoute: typeof AdminMessaggiRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminPoesieRoute: typeof AdminPoesieRoute
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFiabeRoute: AdminFiabeRoute,
  AdminFotografieRoute: AdminFotografieRoute,
  AdminLibriRoute: AdminLibriRoute,
  AdminMessaggiRoute: AdminMessaggiRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminPoesieRoute: AdminPoesieRoute,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AudiolibriPerBambiniRoute: AudiolibriPerBambiniRoute,
  AuthRoute: AuthRoute,
  ChiSonoRoute: ChiSonoRoute,
  ContattiRoute: ContattiRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  FiabeRoute: FiabeRoute,
  FotografieRoute: FotografieRoute,
  LibriRoute: LibriRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ScrittiRoute: ScrittiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
