/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValoriRouteImport } from './routes/valori'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MemindsportRouteImport } from './routes/memindsport'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as GalleriaRouteImport } from './routes/galleria'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as CodroipoCeRouteImport } from './routes/codroipo-ce'
import { Route as BioRouteImport } from './routes/bio'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as Atletica2000RouteImport } from './routes/atletica-2000'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as GalleriaSlugRouteImport } from './routes/galleria.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin.news'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin.gallery'
import { Route as AuthenticatedAdminAgendaRouteImport } from './routes/_authenticated/admin.agenda'

const ValoriRoute = ValoriRouteImport.update({
  id: '/valori',
  path: '/valori',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MemindsportRoute = MemindsportRouteImport.update({
  id: '/memindsport',
  path: '/memindsport',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriaRoute = GalleriaRouteImport.update({
  id: '/galleria',
  path: '/galleria',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const CodroipoCeRoute = CodroipoCeRouteImport.update({
  id: '/codroipo-ce',
  path: '/codroipo-ce',
  getParentRoute: () => rootRouteImport,
} as any)
const BioRoute = BioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const Atletica2000Route = Atletica2000RouteImport.update({
  id: '/atletica-2000',
  path: '/atletica-2000',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriaSlugRoute = GalleriaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GalleriaRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAgendaRoute =
  AuthenticatedAdminAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atletica-2000': typeof Atletica2000Route
  '/auth': typeof AuthRoute
  '/bio': typeof BioRoute
  '/codroipo-ce': typeof CodroipoCeRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/galleria': typeof GalleriaRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/memindsport': typeof MemindsportRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/valori': typeof ValoriRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/galleria/$slug': typeof GalleriaSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
  '/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atletica-2000': typeof Atletica2000Route
  '/auth': typeof AuthRoute
  '/bio': typeof BioRoute
  '/codroipo-ce': typeof CodroipoCeRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/galleria': typeof GalleriaRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/memindsport': typeof MemindsportRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/valori': typeof ValoriRoute
  '/galleria/$slug': typeof GalleriaSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news': typeof NewsIndexRoute
  '/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/atletica-2000': typeof Atletica2000Route
  '/auth': typeof AuthRoute
  '/bio': typeof BioRoute
  '/codroipo-ce': typeof CodroipoCeRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/galleria': typeof GalleriaRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/memindsport': typeof MemindsportRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/valori': typeof ValoriRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/galleria/$slug': typeof GalleriaSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
  '/_authenticated/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/atletica-2000'
    | '/auth'
    | '/bio'
    | '/codroipo-ce'
    | '/contatti'
    | '/cookie-policy'
    | '/galleria'
    | '/meeting'
    | '/memindsport'
    | '/privacy'
    | '/sitemap.xml'
    | '/valori'
    | '/admin'
    | '/galleria/$slug'
    | '/news/$slug'
    | '/news/'
    | '/admin/agenda'
    | '/admin/gallery'
    | '/admin/news'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/atletica-2000'
    | '/auth'
    | '/bio'
    | '/codroipo-ce'
    | '/contatti'
    | '/cookie-policy'
    | '/galleria'
    | '/meeting'
    | '/memindsport'
    | '/privacy'
    | '/sitemap.xml'
    | '/valori'
    | '/galleria/$slug'
    | '/news/$slug'
    | '/news'
    | '/admin/agenda'
    | '/admin/gallery'
    | '/admin/news'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agenda'
    | '/atletica-2000'
    | '/auth'
    | '/bio'
    | '/codroipo-ce'
    | '/contatti'
    | '/cookie-policy'
    | '/galleria'
    | '/meeting'
    | '/memindsport'
    | '/privacy'
    | '/sitemap.xml'
    | '/valori'
    | '/_authenticated/admin'
    | '/galleria/$slug'
    | '/news/$slug'
    | '/news/'
    | '/_authenticated/admin/agenda'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/news'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  Atletica2000Route: typeof Atletica2000Route
  AuthRoute: typeof AuthRoute
  BioRoute: typeof BioRoute
  CodroipoCeRoute: typeof CodroipoCeRoute
  ContattiRoute: typeof ContattiRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  GalleriaRoute: typeof GalleriaRouteWithChildren
  MeetingRoute: typeof MeetingRoute
  MemindsportRoute: typeof MemindsportRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ValoriRoute: typeof ValoriRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/valori': {
      id: '/valori'
      path: '/valori'
      fullPath: '/valori'
      preLoaderRoute: typeof ValoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memindsport': {
      id: '/memindsport'
      path: '/memindsport'
      fullPath: '/memindsport'
      preLoaderRoute: typeof MemindsportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleria': {
      id: '/galleria'
      path: '/galleria'
      fullPath: '/galleria'
      preLoaderRoute: typeof GalleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codroipo-ce': {
      id: '/codroipo-ce'
      path: '/codroipo-ce'
      fullPath: '/codroipo-ce'
      preLoaderRoute: typeof CodroipoCeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio': {
      id: '/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof BioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletica-2000': {
      id: '/atletica-2000'
      path: '/atletica-2000'
      fullPath: '/atletica-2000'
      preLoaderRoute: typeof Atletica2000RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleria/$slug': {
      id: '/galleria/$slug'
      path: '/$slug'
      fullPath: '/galleria/$slug'
      preLoaderRoute: typeof GalleriaSlugRouteImport
      parentRoute: typeof GalleriaRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agenda': {
      id: '/_authenticated/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AuthenticatedAdminAgendaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAgendaRoute: typeof AuthenticatedAdminAgendaRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAgendaRoute: AuthenticatedAdminAgendaRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
  AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GalleriaRouteChildren {
  GalleriaSlugRoute: typeof GalleriaSlugRoute
}

const GalleriaRouteChildren: GalleriaRouteChildren = {
  GalleriaSlugRoute: GalleriaSlugRoute,
}

const GalleriaRouteWithChildren = GalleriaRoute._addFileChildren(
  GalleriaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgendaRoute: AgendaRoute,
  Atletica2000Route: Atletica2000Route,
  AuthRoute: AuthRoute,
  BioRoute: BioRoute,
  CodroipoCeRoute: CodroipoCeRoute,
  ContattiRoute: ContattiRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  GalleriaRoute: GalleriaRouteWithChildren,
  MeetingRoute: MeetingRoute,
  MemindsportRoute: MemindsportRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ValoriRoute: ValoriRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
